WEBTOON_FOR_MALE = [
    ('화산귀환', 'https://comic.naver.com/webtoon/detail?titleId=769209&no=141&week=wed'),
    ('외모지상주의', 'https://comic.naver.com/webtoon/detail?titleId=641253&no=517&week=fri'),
    ('김부장', 'https://comic.naver.com/webtoon/detail?titleId=783053&no=154&week=tue'),
    ('나노머신', 'https://comic.naver.com/webtoon/detail?titleId=747271&no=222&week=thu'),
    ('킬러 배드로', 'https://comic.naver.com/webtoon/detail?titleId=816798&no=56&week=sat'),
    ('퀘스트지상주의', 'https://comic.naver.com/webtoon/detail?titleId=783052&no=154&week=mon'),
    ('입학용병', 'https://comic.naver.com/webtoon/detail?titleId=758150&no=204&week=sun'),
    ('참교육', 'https://comic.naver.com/webtoon/detail?titleId=758037&no=162&week=mon'),
    ('전지적 독자 시점', 'https://comic.naver.com/webtoon/detail?titleId=747269&no=226&week=wed'),
    ('역대급 영지 설계사', 'https://comic.naver.com/webtoon/detail?titleId=777767&no=162&week=fri'),
    ('나 혼자 만렙 뉴비', 'https://comic.naver.com/webtoon/detail?titleId=773797&no=169&week=fri'),
    ('촉법소년', 'https://comic.naver.com/webtoon/detail?titleId=808198&no=80&week=thu'),
    ('윈드브레이커', 'https://comic.naver.com/webtoon/detail?titleId=602910&no=512&week=mon'),
    ('99강화나무몽둥이', 'https://comic.naver.com/webtoon/detail?titleId=792651&no=119&week=sat'),
    ('무직백수 계백순', 'https://comic.naver.com/webtoon/detail?titleId=811721&no=110&week=wed'),
    ('괴력 난신', 'https://comic.naver.com/webtoon/detail?titleId=821597&no=33&week=tue'),
    ('현실퀘스트', 'https://comic.naver.com/webtoon/detail?titleId=783888&no=130&week=thu'),
    ('캐슬2 만인지상', 'https://comic.naver.com/webtoon/detail?titleId=807178&no=68&week=wed'),
    ('일렉시드', 'https://comic.naver.com/webtoon/detail?titleId=717481&no=314&week=wed'),
    ('별이삼샵', 'https://comic.naver.com/webtoon/detail?titleId=737628&no=185&week=sun'),
    ('사신소년', 'https://comic.naver.com/webtoon/detail?titleId=730656&no=243&week=tue'),
    ('백XX', 'https://comic.naver.com/webtoon/detail?titleId=804862&no=91&week=wed'),
    ('1등급 싸움과외', 'https://comic.naver.com/webtoon/detail?titleId=821321&no=36&week=wed'),
    ('신의 탑', 'https://comic.naver.com/webtoon/detail?titleId=183559&no=637&week=mon'),
    ('대장전', 'https://comic.naver.com/webtoon/detail?titleId=829830&no=7&week=wed'),
    ('아수라', 'https://comic.naver.com/webtoon/detail?titleId=826670&no=19&week=sat'),
    ('소년교도소', 'https://comic.naver.com/webtoon/detail?titleId=827335&no=15&week=sun'),
    ('66666년 만에 환생한 흑마법사', 'https://comic.naver.com/webtoon/detail?titleId=775141&no=134&week=wed'),
    ('절대회귀', 'https://comic.naver.com/webtoon/detail?titleId=828715&no=11&week=tue'),
    ('개꿈', 'https://comic.naver.com/webtoon/detail?titleId=818791&no=47&week=sat'),
    ('스터디그룹', 'https://comic.naver.com/webtoon/detail?titleId=721948&no=243&week=sat'),
    ('귀촌리', 'https://comic.naver.com/webtoon/detail?titleId=822573&no=30&week=mon'),
    ('마도전생기', 'https://comic.naver.com/webtoon/detail?titleId=807777&no=81&week=sat'),
    ('회귀한 공작가의 막내도련님의 암살자', 'https://comic.naver.com/webtoon/detail?titleId=821195&no=33&week=mon'),
    ('천마육성', 'https://comic.naver.com/webtoon/detail?titleId=776255&no=139&week=thu'),
    ('죽지 않으려면', 'https://comic.naver.com/webtoon/detail?titleId=772764&no=156&week=fri'),
    ('나쁜사람', 'https://comic.naver.com/webtoon/detail?titleId=750184&no=219&week=wed'),
    ('무사만리행', 'https://comic.naver.com/webtoon/detail?titleId=746857&no=193&week=thu'),
    ('한림체육관', 'https://comic.naver.com/webtoon/detail?titleId=743139&no=194&week=tue'),
    ('열렙전사 3부', 'https://comic.naver.com/webtoon/detail?titleId=817032&no=57&week=fri'),
    ('절대검감', 'https://comic.naver.com/webtoon/detail?titleId=796075&no=98&week=mon'),
    ('소꿉친구 컴플렉스', 'https://comic.naver.com/webtoon/detail?titleId=822640&no=30&week=thu'),
    ('별을 품은 소드마스터', 'https://comic.naver.com/webtoon/detail?titleId=816809&no=56&week=wed'),
    ('아카데미의 천재칼잡이', 'https://comic.naver.com/webtoon/detail?titleId=813564&no=64&week=sun'),
    ('재벌집 막내아들', 'https://comic.naver.com/webtoon/detail?titleId=800770&no=107&week=thu'),
    ('사형집행관', 'https://comic.naver.com/webtoon/detail?titleId=822765&no=27&week=thu'),
    ('나태 공자 노력 천재 되다', 'https://comic.naver.com/webtoon/detail?titleId=772853&no=119&week=sat'),
    ('작두', 'https://comic.naver.com/webtoon/detail?titleId=828294&no=13&week=thu'),
    ('왕따가 격투기를 너무 잘함', 'https://comic.naver.com/webtoon/detail?titleId=806888&no=85&week=wed'),
    ('어느날 갑자기 가슴이 커짐', 'https://comic.naver.com/webtoon/detail?titleId=830015&no=8&week=mon'),
    ('내가 키운 S급들', 'https://comic.naver.com/webtoon/detail?titleId=784248&no=152&week=tue'),
    ('절대군림', 'https://comic.naver.com/webtoon/detail?titleId=832677&no=4&week=sat'),
    ('디펜스 게임의 폭군이 되었다', 'https://comic.naver.com/webtoon/detail?titleId=798182&no=114&week=sat'),
    ('게임 속 바바리안으로 살아남기', 'https://comic.naver.com/webtoon/detail?titleId=808482&no=70&week=thu'),
    ('환생천마', 'https://comic.naver.com/webtoon/detail?titleId=822657&no=31&week=mon'),
    ('천마는 평범하게 살 수 없다', 'https://comic.naver.com/webtoon/detail?titleId=774358&no=122&week=tue'),
    ('멸망 이후의 세계', 'https://comic.naver.com/webtoon/detail?titleId=789979&no=141&week=tue'),
    ('소년법칙', 'https://comic.naver.com/webtoon/detail?titleId=827908&no=14&week=sun'),
    ('용사가 돌아왔다', 'https://comic.naver.com/webtoon/detail?titleId=773459&no=132&week=tue'),
    ('폭력의 왕', 'https://comic.naver.com/webtoon/detail?titleId=824890&no=22&week=mon'),
    ('천재 타자가 강속구를 숨김', 'https://comic.naver.com/webtoon/detail?titleId=807775&no=59&week=mon'),
    ('천화서고 대공자', 'https://comic.naver.com/webtoon/detail?titleId=805193&no=92&week=sun'),
    ('인생존망2', 'https://comic.naver.com/webtoon/detail?titleId=820354&no=40&week=sat'),
    ('아카데미에서 살아남기', 'https://comic.naver.com/webtoon/detail?titleId=820097&no=43&week=fri'),
    ('사천당가의 검신급 소가주가 되었다', 'https://comic.naver.com/webtoon/detail?titleId=822862&no=30&week=wed'),
    ('상남자', 'https://comic.naver.com/webtoon/detail?titleId=751168&no=207&week=fri'),
    ('기기괴괴2', 'https://comic.naver.com/webtoon/detail?titleId=821851&no=31&week=sun'),
    ('별난식당', 'https://comic.naver.com/webtoon/detail?titleId=806189&no=85&week=mon'),
    ('튜토리얼 탑의 고인물', 'https://comic.naver.com/webtoon/detail?titleId=738694&no=223&week=wed'),
    ('육아일기', 'https://comic.naver.com/webtoon/detail?titleId=812354&no=92&week=thu'),
    ('초인의 게임', 'https://comic.naver.com/webtoon/detail?titleId=795658&no=122&week=tue'),
    ('아카데미 플레이어를 죽였다', 'https://comic.naver.com/webtoon/detail?titleId=818434&no=49&week=tue'),
    ('내 여자친구는', 'https://comic.naver.com/webtoon/detail?titleId=824230&no=23&week=wed'),
    ('욕망일기Deep', 'https://comic.naver.com/webtoon/detail?titleId=818448&no=98&week=tue'),
    ('분신으로 자동사냥', 'https://comic.naver.com/webtoon/detail?titleId=799805&no=108&week=sun'),
    ('A.I. 닥터', 'https://comic.naver.com/webtoon/detail?titleId=765804&no=169&week=fri'),
    ('배달왕', 'https://comic.naver.com/webtoon/detail?titleId=823933&no=50&week=thu'),
    ('나 혼자 특성빨로 무한 성장', 'https://comic.naver.com/webtoon/detail?titleId=803909&no=96&week=sun'),
    ('잔불의 기사', 'https://comic.naver.com/webtoon/detail?titleId=768536&no=167&week=mon'),
    ('할배무사와 지존 손녀', 'https://comic.naver.com/webtoon/detail?titleId=817246&no=56&week=thu'),
    ('신입사원 김철수', 'https://comic.naver.com/webtoon/detail?titleId=812594&no=66&week=tue'),
    ('위닝샷!', 'https://comic.naver.com/webtoon/detail?titleId=778578&no=126&week=sun'),
    ('악의 등교', 'https://comic.naver.com/webtoon/detail?titleId=808272&no=59&week=wed'),
    ('천하제일 대사형', 'https://comic.naver.com/webtoon/detail?titleId=802278&no=102&week=fri'),
    ('용사보다 너무 강해서 힘을 숨김', 'https://comic.naver.com/webtoon/detail?titleId=814213&no=58&week=sun'),
    ('사시미 한 자루로 아카데미를 씹어먹음', 'https://comic.naver.com/webtoon/detail?titleId=829875&no=9&week=thu'),
    ('마음의소리2', 'https://comic.naver.com/webtoon/detail?titleId=814543&no=61&week=tue'),
    ('체크포인트', 'https://comic.naver.com/webtoon/detail?titleId=677452&no=97&week=fri'),
    ('어느 마법사의 식당', 'https://comic.naver.com/webtoon/detail?titleId=818888&no=46&week=wed'),
    ('운명을 보는 회사원', 'https://comic.naver.com/webtoon/detail?titleId=797443&no=95&week=wed'),
    ('펜홀더', 'https://comic.naver.com/webtoon/detail?titleId=814587&no=59&week=fri'),
    ('백투더찬비', 'https://comic.naver.com/webtoon/detail?titleId=826322&no=21&week=thu'),
    ('좋아 죽어!', 'https://comic.naver.com/webtoon/detail?titleId=821192&no=74&week=tue'),
    ('랜덤채팅의 그녀!', 'https://comic.naver.com/webtoon/detail?titleId=702608&no=351&week=finish'),
    ('서울 자가에 대기업 다니는 김 부장 이야기', 'https://comic.naver.com/webtoon/detail?titleId=819929&no=42&week=tue'),
    ('왕의 힘으로 회귀한다', 'https://comic.naver.com/webtoon/detail?titleId=817958&no=51&week=sat'),
    ('나 혼자 네크로맨서', 'https://comic.naver.com/webtoon/detail?titleId=780170&no=148&week=thu'),
    ('히어로 킬러', 'https://comic.naver.com/webtoon/detail?titleId=766563&no=188&week=fri'),
    ('그레이마크', 'https://comic.naver.com/webtoon/detail?titleId=829462&no=9&week=sun'),
    ('2회차 환관이 남성을 되찾음', 'https://comic.naver.com/webtoon/detail?titleId=832566&no=3&week=sun'),
    ('더블클릭', 'https://comic.naver.com/webtoon/detail?titleId=769663&no=165&week=mon'),
    ('칼에 취한 밤을 걷다', 'https://comic.naver.com/webtoon/detail?titleId=795542&no=123&week=wed'),
    ('천재 무림 트레이너', 'https://comic.naver.com/webtoon/detail?titleId=824295&no=24&week=sun'),
    ('사신', 'https://comic.naver.com/webtoon/detail?titleId=799837&no=90&week=fri'),
    ('먹뀌싸', 'https://comic.naver.com/webtoon/detail?titleId=820888&no=38&week=sun'),
    ('시한부 천재 암흑기사', 'https://comic.naver.com/webtoon/detail?titleId=809625&no=72&week=thu'),
    ('염라강림', 'https://comic.naver.com/webtoon/detail?titleId=818192&no=50&week=tue'),
    ('짜장 한 그릇에 제갈세가 데릴사위', 'https://comic.naver.com/webtoon/detail?titleId=822114&no=32&week=sat'),
    ('게임 최강 트롤러', 'https://comic.naver.com/webtoon/detail?titleId=801698&no=100&week=thu'),
    ('흑사', 'https://comic.naver.com/webtoon/detail?titleId=828170&no=13&week=wed'),
    ('회귀한 천재 헌터의 슬기로운 청소생활', 'https://comic.naver.com/webtoon/detail?titleId=796827&no=97&week=thu'),
    ('오늘만 사는 기사', 'https://comic.naver.com/webtoon/detail?titleId=824543&no=23&week=sat'),
    ('사람의 탈', 'https://comic.naver.com/webtoon/detail?titleId=822198&no=32&week=tue'),
]

WEBTOON_FOR_FEMALE = [
    ('소꿉친구 컴플레스', 'https://comic.naver.com/webtoon/detail?titleId=822640&no=30&week=thu'),
    ('육아일기', 'https://comic.naver.com/webtoon/detail?titleId=812354&no=92&week=thu'),
    ('시든 꽃에 눈물을', 'https://comic.naver.com/webtoon/detail?titleId=827190&no=16&week=sat'),
    ('재혼 황후', 'https://comic.naver.com/webtoon/detail?titleId=735661&no=189&week=fri'),
    ('마루는 강쥐', 'https://comic.naver.com/webtoon/detail?titleId=796152&no=114&week=tue'),
    ('어느날 갑자기 가슴이 커짐', 'https://comic.naver.com/webtoon/detail?titleId=830015&no=8&week=mon'),
    ('왕과의 야행', 'https://comic.naver.com/webtoon/detail?titleId=817859&no=49&week=mon'),
    ('개꿈', 'https://comic.naver.com/webtoon/detail?titleId=818791&no=47&week=sat'),
    ('똑 닮은 딸', 'https://comic.naver.com/webtoon/detail?titleId=774866&no=125&week=mon'),
    ('시월드가 내게 집착한다', 'https://comic.naver.com/webtoon/detail?titleId=785251&no=123&week=sun'),
    ('소녀의 세계', 'https://comic.naver.com/webtoon/detail?titleId=654774&no=434&week=mon'),
    ('버림받은 왕녀의 은밀한 침실', 'https://comic.naver.com/webtoon/detail?titleId=796867&no=117&week=mon'),
    ('우아한 욕망', 'https://comic.naver.com/webtoon/detail?titleId=813552&no=56&week=mon'),
    ('화산귀환', 'https://comic.naver.com/webtoon/detail?titleId=769209&no=141&week=wed'),
    ('쌉초의 난', 'https://comic.naver.com/webtoon/detail?titleId=823195&no=57&week=wed'),
    ('청춘 러브썸', 'https://comic.naver.com/webtoon/detail?titleId=828920&no=9&week=tue'),
    ('조조코믹스', 'https://comic.naver.com/webtoon/detail?titleId=774862&no=153&week=wed'),
    ('아홉수 우리들', 'https://comic.naver.com/webtoon/detail?titleId=724815&no=243&week=sat'),
    ('날 닮은 아이', 'https://comic.naver.com/webtoon/detail?titleId=822111&no=32&week=sun'),
    ('충족', 'https://comic.naver.com/webtoon/detail?titleId=827814&no=3&week=dailyPlus'),
    ('시한부인 줄 알았어요', 'https://comic.naver.com/webtoon/detail?titleId=801711&no=67&week=tue'),
    ('미친 짓인 줄 알면서도', 'https://comic.naver.com/webtoon/detail?titleId=824200&no=3&week=dailyPlus'),
    ('커플브레이커', 'https://comic.naver.com/webtoon/detail?titleId=804832&no=68&week=fri'),
    ('못 잡아먹어서 안달', 'https://comic.naver.com/webtoon/detail?titleId=817247&no=52&week=tue'),
    ('중간에서 만나', 'https://comic.naver.com/webtoon/detail?titleId=808455&no=55&week=wed'),
    ('언니 이번 생엔 내가 왕비야', 'https://comic.naver.com/webtoon/detail?titleId=798917&no=113&week=fri'),
    ('사내연애 사절', 'https://comic.naver.com/webtoon/detail?titleId=814512&no=57&week=thu'),
    ('작전명 순정', 'https://comic.naver.com/webtoon/detail?titleId=793275&no=110&week=sat'),
    ('자매전쟁', 'https://comic.naver.com/webtoon/detail?titleId=798664&no=79&week=sun'),
    ('19년지기의 하룻밤', 'https://comic.naver.com/webtoon/detail?titleId=828043&no=3&week=dailyPlus'),
    ('여우놀이', 'https://comic.naver.com/webtoon/detail?titleId=768469&no=106&week=fri'),
    ('내향남녀', 'https://comic.naver.com/webtoon/detail?titleId=812629&no=67&week=thu'),
    ('흔한 빙의물인 줄 알았다', 'https://comic.naver.com/webtoon/detail?titleId=808018&no=74&week=wed'),
    ('청춘계시록', 'https://comic.naver.com/webtoon/detail?titleId=802079&no=87&week=sun'),
    ('전남편의 미친개를 길들였다', 'https://comic.naver.com/webtoon/detail?titleId=804160&no=93&week=fri'),
    ('문제적 왕자님', 'https://comic.naver.com/webtoon/detail?titleId=800046&no=84&week=fri'),
    ('하루만 네가 되고 싶어', 'https://comic.naver.com/webtoon/detail?titleId=738487&no=232&week=tue'),
    ('이기적 연애론', 'https://comic.naver.com/webtoon/detail?titleId=824888&no=20&week=wed'),
    ('베이비 폭군', 'https://comic.naver.com/webtoon/detail?titleId=807019&no=77&week=wed'),
    ('세기말 풋사과 보습학원', 'https://comic.naver.com/webtoon/detail?titleId=761722&no=150&week=fri'),
    ('토마토가 돼라', 'https://comic.naver.com/webtoon/detail?titleId=805702&no=82&week=mon'),
    ('학식의 꿈', 'https://comic.naver.com/webtoon/detail?titleId=818403&no=49&week=mon'),
    ('어디까지 괜찮아', 'https://comic.naver.com/webtoon/detail?titleId=821520&no=3&week=dailyPlus'),
    ('가장 썩은 것을 줄게', 'https://comic.naver.com/webtoon/detail?titleId=821814&no=33&week=fri'),
    ('팔이피플', 'https://comic.naver.com/webtoon/detail?titleId=774863&no=124&week=mon'),
    ('별이삼샵', 'https://comic.naver.com/webtoon/detail?titleId=737628&no=185&week=sun'),
    ('수상한 다이어트 클럽', 'https://comic.naver.com/webtoon/detail?titleId=821626&no=28&week=mon'),
    ('긁지 않은 복권', 'https://comic.naver.com/webtoon/detail?titleId=828908&no=10&week=tue'),
    ('사랑하는 나의 억압자', 'https://comic.naver.com/webtoon/detail?titleId=822080&no=35&week=sat'),
    ('참교육', 'https://comic.naver.com/webtoon/detail?titleId=758037&no=162&week=mon'),
    ('나를 바꿔줘', 'https://comic.naver.com/webtoon/detail?titleId=733280&no=266&week=sat'),
    ('대충 캠퍼스로맨스임', 'https://comic.naver.com/webtoon/detail?titleId=797184&no=101&week=sat'),
    ('집이 없어', 'https://comic.naver.com/webtoon/detail?titleId=721433&no=270&week=finish'),
    ('정신 차려, 전승연', 'https://comic.naver.com/webtoon/detail?titleId=832243&no=4&week=mon'),
    ('작두', 'https://comic.naver.com/webtoon/detail?titleId=828294&no=13&week=thu'),
    ('유부 감자', 'https://comic.naver.com/webtoon/detail?titleId=822556&no=64&week=tue'),
    ('킬러 배드로', 'https://comic.naver.com/webtoon/detail?titleId=816798&no=57&week=sat'),
    ('암호는 002!', 'https://comic.naver.com/webtoon/detail?titleId=819223&no=42&week=tue'),
    ('백작가의 비밀스런 시녀님', 'https://comic.naver.com/webtoon/detail?titleId=830106&no=6&week=tue'),
    ('악마의 소원', 'https://comic.naver.com/webtoon/detail?titleId=816685&no=3&week=dailyPlus'),
    ('인과관계', 'https://comic.naver.com/webtoon/detail?titleId=789652&no=137&week=wed'),
    ('무직백수 계백순', 'https://comic.naver.com/webtoon/detail?titleId=811721&no=110&week=wed'),
    ('소공녀 민트', 'https://comic.naver.com/webtoon/detail?titleId=787061&no=118&week=finish'),
    ('내가 키운 미친개에게 감금당했다', 'https://comic.naver.com/webtoon/detail?titleId=832320&no=4&week=thu'),
    ('나의 신은 욕망꾸러기', 'https://comic.naver.com/webtoon/detail?titleId=818567&no=48&week=wed'),
    ('하는 사이', 'https://comic.naver.com/webtoon/detail?titleId=823437&no=27&week=fri'),
    ('내 여자친구는', 'https://comic.naver.com/webtoon/detail?titleId=824230&no=23&week=wed'),
    ('잘 헤어지는 방법', 'https://comic.naver.com/webtoon/detail?titleId=826348&no=20&week=mon'),
    ('엔드리스 서머', 'https://comic.naver.com/webtoon/detail?titleId=829418&no=8&week=wed'),
    ('순정빌런', 'https://comic.naver.com/webtoon/detail?titleId=797731&no=104&week=thu'),
    ('삼이는 재생한다', 'https://comic.naver.com/webtoon/detail?titleId=822874&no=29&week=thu'),
    ('나 혼자 탑에서 농사', 'https://comic.naver.com/webtoon/detail?titleId=808389&no=76&week=fri'),
    ('사자의 서', 'https://comic.naver.com/webtoon/detail?titleId=823737&no=25&week=fri'),
    ('죽거나 혹은 사랑에 빠지거나', 'https://comic.naver.com/webtoon/detail?titleId=819696&no=43&week=sun'),
    ('순수한 동거생활', 'https://comic.naver.com/webtoon/detail?titleId=797937&no=104&week=finish'),
    ('온리호프', 'https://comic.naver.com/webtoon/detail?titleId=800796&no=91&week=fri'),
    ('수희0(tngmlek0)', 'https://comic.naver.com/webtoon/detail?titleId=774831&no=167&week=sun'),
    ('욕망을 가르쳐주세요', 'https://comic.naver.com/webtoon/detail?titleId=829238&no=9&week=tue'),
    ('폭군님은 착하게 살고 싶어', 'https://comic.naver.com/webtoon/detail?titleId=801736&no=87&week=fri'),
    ('피폐물을 힐링물로 만드는 방법', 'https://comic.naver.com/webtoon/detail?titleId=826381&no=19&week=mon'),
    ('좋아 죽어!', 'https://comic.naver.com/webtoon/detail?titleId=821192&no=74&week=tue'),
    ('진돌히디만화', 'https://comic.naver.com/webtoon/detail?titleId=822095&no=33&week=wed'),
    ('가공낙원', 'https://comic.naver.com/webtoon/detail?titleId=830053&no=5&week=tue'),
    ('탑아이돌의 막내 멤버가 되었다', 'https://comic.naver.com/webtoon/detail?titleId=819748&no=41&week=sat'),
    ('검은 늑대가 나를 부르면', 'https://comic.naver.com/webtoon/detail?titleId=823439&no=25&week=thu'),
    ('다른 남자 아이로 키우겠어', 'https://comic.naver.com/webtoon/detail?titleId=832303&no=3&week=dailyPlus'),
    ('너의 미소가 함정', 'https://comic.naver.com/webtoon/detail?titleId=741467&no=143&week=fri'),
    ('사랑은 없는 것처럼', 'https://comic.naver.com/webtoon/detail?titleId=805481&no=65&week=sun'),
    ('아임 파인 땡큐, 앤유', 'https://comic.naver.com/webtoon/detail?titleId=829495&no=7&week=sun'),
    ('홍시는 날 좋아해!', 'https://comic.naver.com/webtoon/detail?titleId=703839&no=287&week=sat'),
    ('대리 황후지만 첫날밤을 보내버렸다', 'https://comic.naver.com/webtoon/detail?titleId=829704&no=3&week=dailyPlus'),
    ('피폐물 남주의 엄마가 되었다', 'https://comic.naver.com/webtoon/detail?titleId=818368&no=51&week=sun'),
    ('귀촌리', 'https://comic.naver.com/webtoon/detail?titleId=822573&no=30&week=mon'),
    ('촉법소년', 'https://comic.naver.com/webtoon/detail?titleId=808198&no=80&week=thu'),
    ('역대급 영지 설계사', 'https://comic.naver.com/webtoon/detail?titleId=777767&no=162&week=fri'),
    ('어린이집 다니는 구나', 'https://comic.naver.com/webtoon/detail?titleId=817945&no=100&week=mon'),
    ('불완전 신데렐라물', 'https://comic.naver.com/webtoon/detail?titleId=819020&no=45&week=sun'),
    ('여동생은 오늘 밤 나를 간택한다', 'https://comic.naver.com/webtoon/detail?titleId=822557&no=32&week=fri'),
    ('남주의 정석', 'https://comic.naver.com/webtoon/detail?titleId=827323&no=17&week=sun'),
    ('2024 루키 단편선', 'https://comic.naver.com/webtoon/detail?titleId=831770&no=6&week=mon'),
    ('약탈 신부', 'https://comic.naver.com/webtoon/detail?titleId=804329&no=94&week=fri'),
    ('일렉시드', 'https://comic.naver.com/webtoon/detail?titleId=717481&no=314&week=wed'),
    ('빛나는 나나나나', 'https://comic.naver.com/webtoon/detail?titleId=818205&no=49&week=tue'),
    ('에밀리의 저택', 'https://comic.naver.com/webtoon/detail?titleId=824237&no=24&week=thu'),
    ('랑데뷰', 'https://comic.naver.com/webtoon/detail?titleId=778967&no=134&week=sun'),
    ('마른 가지에 바람처럼', 'https://comic.naver.com/webtoon/detail?titleId=748535&no=198&week=wed'),
    ('황후의 짐승간택', 'https://comic.naver.com/webtoon/detail?titleId=828127&no=12&week=mon'),
    ('천만청춘', 'https://comic.naver.com/webtoon/detail?titleId=828402&no=14&week=tue'),
    ('기자매', 'https://comic.naver.com/webtoon/detail?titleId=823285&no=27&week=thu'),
    ('흑요석의 신부', 'https://comic.naver.com/webtoon/detail?titleId=814310&no=61&week=fri'),
    ('첫눈에 반한 건 아니지만', 'https://comic.naver.com/webtoon/detail?titleId=830637&no=6&week=thu'),
    ('시바, 만만치 않다', 'https://comic.naver.com/webtoon/detail?titleId=827614&no=15&week=wed'),
]